### ISSUE TITLE
can't import the necessary code from pydmrs

### ISSUE THREAD

**Issue by rizar** [AlexKuhnle/ShapeWorld#10]
When I install pydmrs from PyPi I get an [error](https://gist.github.com/rizar/e526b3e9fe99d4704ea0e251b2a7cd70). When I install it from github, I get [another error](https://gist.github.com/rizar/54ff083dbd271503653ddcfc38b1a179).

**Comment by AlexKuhnle** [comment]
Hi @rizar,
The problem is that I use a separate Python2-compatible branch of `pydmrs`, which by now contains a few other improvements that I should add to master at some point. The best way to install ShapeWorld is to follow 'Getting started', which clones the right version of `pydmrs` as a sub-repo via `--recursive`:
```bash
git clone --recursive https://github.com/AlexKuhnle/ShapeWorld.git
pip3 install -e ShapeWorld  # optional: ShapeWorld[full] or ShapeWorld[full-gpu]
```
Hope that helps, and please let me know if it doesn't.

**Comment by rizar** [comment]
Thanks for the quick reply, @AlexKuhnle . Switching to the `python2` branch did the job, but for the record I'm using Python 3, so such a workaround is rather counter intuitive. I can see though that you do have installation instructions in `README.md` which I missed, sorry about that.

**Comment by AlexKuhnle** [comment]
The problem is that `pydmrs` only works with Python 3, which I use myself as well, but I nevertheless would like to support Python 2. Hence the `python2` branch of `pydmrs` which works with both Python 2 and 3. Unfortunately, this can cause confusion if the `--recursive` option is not applied. I'm sure I would miss it myself... :-)  I'll see whether this situation can be improved somehow.
