### ISSUE TITLE
"no such instance as `root_gen' available"

### ISSUE THREAD

**Issue by gstoica27** [AlexKuhnle/ShapeWorld#27]
Hi,

Thanks for this great dataset! 

I am not able to generate/load any data. Running the provided "Integration into Python code" code, I receive this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/georgestoica/Desktop/Research/ShapeWorld/shapeworld/dataset.py", line 1360, in generate
    captions = self.caption_realizer.realize(captions=captions)
  File "/Users/georgestoica/Desktop/Research/ShapeWorld/shapeworld/realizers/dmrs/realizer.py", line 317, in realize
    assert len(caption_strings) == len(captions), '\n'.join(stdout_data) + '\n' + '\n'.join(stderr_data)
AssertionError: 
roots: no such instance as `root_gen' available
NOTE: transfer did 0 successful unifies and 0 failed ones
```

Upon closer inspection, it appears that "root_gen" is an argument passed to this function call,
```python
ace = subprocess.Popen([self.ace_path, '-g', self.erg_path, '-1e'] + self.ace_arguments, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
On line 260 of "ShapeWorld/shapeworld/realizers/dmrs/realizer.py".

I haven't been able to find any solutions online -- can't find anything related to "root_gen" and python subprocesses. 

I was wondering if by any chance there were any known solutions to this? I really wanted to use this dataset for our research. 

Any help would be very greatly appreciated! Thanks very much!

**Comment by AlexKuhnle** [comment]
Hi @gstoica27,

That looks like a problem with ACE/ERG, so the grammar and parser used to generate language. I assume you haven't modified these, or installed ACE separately or so? Few questions:

What OS are you using? Has the `english.dat` been correctly unpacked [here](https://github.com/AlexKuhnle/ShapeWorld/tree/master/shapeworld/realizers/dmrs/languages) (see the `.gz` archives, which should be unpacked on first use). I also assume `ace` has been correctly unpacked [here](https://github.com/AlexKuhnle/ShapeWorld/tree/master/shapeworld/realizers/dmrs/resources)? What happens if you simply remove [this line](https://github.com/AlexKuhnle/ShapeWorld/blob/master/shapeworld/realizers/dmrs/languages/english.json#L2), in which the `root_gen` argument is added?

If you're using macOS, do you have access to a Linux system where you could try to run it?

**Comment by gstoica27** [comment]
Hi,

Thanks for the quick reply! 

I am on primarily on macOS, although I checked and it is working on our linux servers. 

Regarding the .gz file, I didn't realize they were supposed to be unpacked. Unfortunately, unpacking them does not resolve the issue. And while removing the line suggested in "english.json" sidesteps the "root_gen" error, the assertion still fails because the caption_strings list is empty. 

However -- this is very strange to me, if I run [integrate_language.sh](https://github.com/AlexKuhnle/ShapeWorld/blob/master/shapeworld/realizers/dmrs/languages/integrate_language.sh), ["compile.sh"](https://github.com/AlexKuhnle/ShapeWorld/blob/master/shapeworld/realizers/dmrs/languages/compilation/compile.sh) (both throw expected errors), create a new virtual environment, and rerun "pip install -e ." in the new environment, the "root_gen" error is gone. 

Instead, there is this different assertion error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/georgestoica/Desktop/shapeworld3/ShapeWorld/shapeworld/dataset.py", line 1360, in generate
    captions = self.caption_realizer.realize(captions=captions)
  File "/Users/georgestoica/Desktop/shapeworld3/ShapeWorld/shapeworld/realizers/dmrs/realizer.py", line 317, in realize
    assert len(caption_strings) == len(captions), '\n'.join(stdout_data) + '\n' + '\n'.join(stderr_data)
AssertionError: 
this does not appear to be a grammar image.
NOTE: transfer did 0 successful unifies and 0 failed ones
```

Do you know if there is anything else besides unpacking the .gz files suggested that should be performed? Or where this error may be coming from? Should I make a new thread for this? 


Thanks again for replying and the suggestions! Any advice would be greatly appreciated!

**Comment by AlexKuhnle** [comment]
The  `.gz` files are automatically unpacked the first time you call the code (I hope), so you shouldn't need to unpack them manually. And given that you could call `ace`, since you got the `root_gen` exception, I assume that happened.

The `integrate_language.sh` script should not be used, but the `compile.sh` may be part of the solution. Since you're using macOS, I think the problem is the grammar file. Unfortunately, it seems that the grammar file `english.dat` is not compatible between OSs, which I didn't realise for a long while since I was always working on Linux. That's why there now is a separate `.gz` file for Linux vs Mac. Now the problem may be that the provided Mac version of the grammar file is either outdated or not compatible with your system. What you hence could try is following the two steps [here](https://github.com/AlexKuhnle/ShapeWorld/tree/master/shapeworld/realizers/dmrs/languages/compilation), where the second involves `compile.sh`, so this will compile a new grammar file. If that doesn't work for you, I may also be able to reproduce the problem and see whether I can fix it. (And if it does work, we can talk about a PR to update the Mac version of the grammar file :-).

All this is due to the language generation system using a formal-grammar-based generation system based on separate tools (ERG: big grammar for English, ACE: parser/generator to use the grammar), in case you're curious. If it works, it's great, but unfortunately it can take a bit to get it to work (but I hope it eventually does work^^).

**Comment by gstoica27** [comment]
Ah ok, I see. 

Unfortunately, I am getting a seg fault when running the second step of [your suggestions](https://github.com/AlexKuhnle/ShapeWorld/tree/master/shapeworld/realizers/dmrs/languages/compilation). 

Here is the exact error:
```
reading configuration       from `/Users/georgestoica/Desktop/shapeworld3/ShapeWorld/shapeworld/realizers/dmrs/languages/compilation/erg-shapeworld/ace/config.tdl'
reading types               from `/Users/georgestoica/Desktop/shapeworld3/ShapeWorld/shapeworld/realizers/dmrs/languages/compilation/erg-shapeworld/ace/../mtr.tdl'
grammar version             ERG (trunk)
./compile.sh: line 15: 78740 Segmentation fault: 11  ../../resources/ace -G ../english.dat -g $2/ace/config.tdl
```

Just to double check that I am running things in the order that is expected, I did the following:
1. recursive clone the repository as described in the first step of [this](https://github.com/AlexKuhnle/ShapeWorld) readme
2. pip install -e . as described in step two of ^.
3. running the two steps as suggested [here](https://github.com/AlexKuhnle/ShapeWorld/tree/master/shapeworld/realizers/dmrs/languages/compilation).

Is there a different order/steps that you would recommend trying as well? I'd be happy to give you anything you might need/help to resolve these issues :). This all also helps me get a better understanding of everything so there isn't any problem. 

Thanks!

**Comment by AlexKuhnle** [comment]
Sorry for the late reply. I don't know where the `pip install` step comes in, but it doesn't look like the error is related to that. Maybe you could manually make sure that the right `ace` executable is in the `resources` folder by manually (re)unpacking the mac ace zip file. Otherwise I'm not sure what the problem could be (I can still potentially try it myself one of these days, just to see what happens). If nothing helps, maybe Linux for data generation is the best way to go, although that would be annoying of course.

**Comment by AlexKuhnle** [comment]
Is this still a problem?

**Comment by gstoica27** [comment]
Hi, yes sorry. I couldn't get it working on mac, even with the zip file unpacking, But you're right that everything else (aside from generation) works on mac, which is fine for my use cases.

**Comment by AlexKuhnle** [comment]
Okay, I guess this can be closed then...

**Comment by hughperkins** [comment]
Opinion: I think the readme should make it *really* obvious that shapeworld doesnt run on a Mac. I spent several hours fightning with this issue, looking at the code etc, before wandering into the Issues, and finding that it simply doesnt run on a Mac.

On linux, stuff "just works".

I think you might consider actually adding to the top of `generate.py` ( as I have done, in order to not accidentally contaminate the data files with mac files), code to prevent running on Mac at all:

```
if __name__ == '__main__':
    if os.uname()[0] == 'Darwin':
        raise Exception('Mac not supported. If you wish to continue, then please comment out this Exception,'
                        ' but be aware that you will be entering uncharted territory')
```

**Comment by AlexKuhnle** [comment]
Sorry to hear that, and the exception is a very good idea. If you've already done so, would you mind creating a PR with the change? Otherwise I can also do that later...

**Comment by hughperkins** [comment]
Sure! https://github.com/AlexKuhnle/ShapeWorld/pull/30
