### ISSUE TITLE
How to custom our own dataset?

### ISSUE THREAD

**Issue by willanxywc** [AlexKuhnle/ShapeWorld#3]
HI~
ShapeWorld is really a inspriational work. But I have some tips on the dataset building.  Since it's published as a python library,  maybe some annotations or demonstations for the captioner and realizers on how to use them to produce customed datasets would be better?
For example I need to generate simple captions like "There are 3 more triangles than circles". I didn't find such style in given agreement dataset. And I can't really figure out which captioners should I use, or how to configure the given dataset.pys. Even when I change the given vocabulary in datasets/agreement/**.py I find I should also change the vocabulary in realizer and world builder.  Other issues come like this, the interaction between the captioner/realizer/world_generator. 
I think other users may also apprectiate a demo with simple annotations on how to use the submodels, if it's not too much bother.
Sincerely

**Comment by AlexKuhnle** [comment]
Hi @willanxywc,

Documentation/tutorials is definitely something which requires more work, and it's useful to know how people want to actually use it (because I probably don't have time to document everything in as much detail as is required).

Your example of "There are 3 more triangles than circles" is similar to some captions in the 'Quantification Count Simple' dataset ([link](https://rawgit.com/AlexKuhnle/ShapeWorld/master/examples/agreement/quantification_count_simple/data.html) to example data in the readme, cf first line, although there is currently an annoying realization bug producing weird word order, which I hope to fix soon). If you then check out the corresponding dataset file, you find the `ComparativeQuantifierCaptioner` [here](https://github.com/AlexKuhnle/ShapeWorld/blob/master/shapeworld/datasets/agreement/quantification_count_simple.py#L57). Modifying e.g. the `CaptionerMixer` below to only focus on this captioner (`[0, 0, 1]`) would get you data of this form. Comparing this to the 'non-simple' version of the dataset [here](https://github.com/AlexKuhnle/ShapeWorld/blob/master/shapeworld/datasets/agreement/quantification_count.py) might also be insightful.

These kind of modifications should be possible without going too deep into the code. It is however not exactly of the pattern that you want, and adding new patterns is, unfortunately, not that easy. Does the former kind of 'light' modification suffice for what you want to achieve?

**Comment by AlexKuhnle** [comment]
I'm curious about the problem with vocabulary causing problems in realizer and world builder and other issues of this kind... What exactly did go wrong there?

**Comment by willanxywc** [comment]
Well, it was that I modified the vocabulary in dataset and get a missing word error, 

`  File "generate.py", line 142, in <module>
    generated = dataset.generate(n=args.instances, mode=mode, noise_range=args.pixel_noise, include_model=args.include_model, alternatives=True)
  File "/home/jysen/code/ShapeWorld/shapeworld/dataset.py", line 803, in generate
    assert not missing_words and max_caption_size <= caption_size
`

my fault = =? and I think I could get it fixed. I quoted this because I sometimes get confused when, as you say, add new patterns.  Could you give me some suggestions on where to begin, do I need to start with DMRS?  Which part do you start with when you write a new pattern?

Whats more, I believe you have found this order issue, in several quantification datasets, generated captions which start with color or number tend to be wrong ordered.  
```
cyan four less than crosses shapes are behind a cross .
green twice as many shapes as circles are behind a semicircle .
five less crosses than pentagons are blue .
```
And thks for the nice work and timely reply~

**Comment by AlexKuhnle** [comment]
Yes, the latter is a bug in the grammar, and will probably be fixed by next week. Regarding your error, it probably tells you what's the missing words and/or what's the max caption size, which you can then adapt in the dataset's constructor. I think the datasets should work as they are, but modifications might mean you have to add words.

If you want to add a new 'pattern', it depends a bit what the pattern exactly is: If you want to, say, produce captions of the form "Two squares are to the left of a green triangle.", then that can be achieved with existing and defined caption components, in fact it is a subset of the 'Quantification Count' dataset. If you want to add new phrases or so, your above example for instance, then you have to start with adding the DMRS graph components. If it fits into existing `Caption` objects like `Relation` (something like *'to the left of X'*), then it works without too many issues, but if you need to define a new `Caption` subclass to be able to properly define the phrase, then you need to do some more integration work. I always welcome good ideas for new caption types, and happy to integrate them or be of help, so let me know if you have something in mind.

**Comment by AlexKuhnle** [comment]
Outdated
