### ISSUE TITLE
Error when `worlds_per_instance > 1`

### ISSUE THREAD

**Issue by jayelm** [AlexKuhnle/ShapeWorld#6]
I was toying around with `worlds_per_instance`:

```python
from shapeworld import Dataset

dataset = Dataset.create(dtype='agreement', name='multishape',
                         worlds_per_instance=5)
generated = dataset.generate(n=3, mode='train', include_model=True)
```

But I get the following error:

```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    generated = dataset.generate(n=3, mode='train', include_model=True)
  File "/local/scratch/jlm95/ShapeWorld/shapeworld/dataset.py", line 901, in generate
    batch['agreement'][i].append(float(correct))
AttributeError: 'numpy.float32' object has no attribute 'append'
```

This seems to be because `batch['agreement']` is initialized to a single float for each instance, e.g. `array([1., 1., 1.], dtype=float32)`, and can't be appended to.

`batch['agreement']` is initialized in `zero_batch` based on the datatypes provided by `self.values`, does the datatype for `agreement` need to be changed to a `vector(float)` when `worlds_per_instance > 1`?

**Comment by AlexKuhnle** [comment]
I just looked into this, and I think it's probably because [this line](https://github.com/AlexKuhnle/ShapeWorld/blob/master/shapeworld/dataset.py#L900) should include an `if alternatives and (...):`. I will fix this in the next update. Generally, you should set `dataset.generate(..., alternatives=True)`, otherwise it will be ignored. Probably not the most intuitive default setting, so might improve that in the next update as well.
